### ISSUE TITLE
couldnt figure out the issue while running

### ISSUE THREAD

**Issue by thinksabin** [ozonru/dtrack-audit#7]
command used:
`Users/thinksabin/go/bin/dtrack-audit -a -i bom.xml -k PBohV8SZab8Rel5j1FEHZEI9wjDMdC1g -u http://192.168.43.221:8080`

error:
```
Send SBOM file to Dependency Track for audit.

Usage of program: ...... 
Fields marked with (*) are required.
```
Environment variable  DTRACK_AUTO_CREATE_PROJECT is already set.
Help required. thanks.

**Comment by oxdef** [comment]
@thinksabin Sorry for the delayed response. Is the problem still actual?

**Comment by thinksabin** [comment]
Let me check again and will let you know. Thanks.

**Comment by oxdef** [comment]
@thinksabin  Please, reopen this issue if the problem is still actual.
